import builtins from 'builtin-modules'
import esbuild from 'esbuild'
import process from 'node:process'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const isProd = process.argv[2] === 'production'

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	outdir: './',
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins,
	],
	plugins:
		process.env.NODE_ENV === 'development'
			? [
					{
						name: 'copy-plugin',
						setup: (build) => {
							build.onStart(async () => {
								const SOURCE_DIR = process.cwd()
								const DEST_DIR = process.env.LOCAL_PLUGIN_PATH
								if (!DEST_DIR) {
									throw new Error('LOCAL_PLUGIN_PATH is not set')
								}
								const { exitCode } = await Bun.$`echo 'starting rebuild...' \
					&& mkdir -p ${DEST_DIR} \
					&& rsync -av --include="main.js" --include="manifest.json" --exclude="*" ${SOURCE_DIR}/ ${DEST_DIR}/`

								if (exitCode !== 0) {
									throw new Error('Failed to copy plugin files')
								}
							})
						},
					},
				]
			: undefined,
	format: 'cjs',
	platform: 'node',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: isProd ? false : 'inline',
	treeShaking: true,
})

if (isProd) {
	await context.rebuild()
	process.exit(0)
} else {
	await context.watch()
}
